org.gradle.jvmargs=-Xmx4096m
manifestUrl=https://launchermeta.mojang.com/mc/game/version_manifest.json

# 1 week
cacheValidMillis=604800000

# Change to invalidate mappings cache on CI
gameVersion=26.2

systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7897
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7897